services:
  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: php:8.3-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "\
        apt-get update && \
        apt-get install -y unzip git && \
        docker-php-ext-install pdo_mysql && \
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
        if [ -f composer.json ]; then composer install; fi && \
        php-fpm"

  db:
    image: mysql:8.0
    environment:
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - .:/var/www/html
      - mysql_data:/var/lib/mysql

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver
    depends_on:
      - db
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver_data:
  mysql_data:
