services:
  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: php:8.3-fpm
    volumes:
      - .:/var/www/html
    command: >
      sh -c "docker-php-ext-install pdo_mysql && php-fpm"

  db:
    image: mysql:8.0
    environment:
      TZ: UTC
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: uninove
      MYSQL_ROOT_PASSWORD: root
      MYSQL_COLLATION: utf8mb4_0900_ai_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - .:/var/www/html
      - mysql_data:/var/lib/mysql

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver
    depends_on:
      - db
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver_data:
  mysql_data:
